apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-worker-pvc
  namespace: llm-worker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
