---
apiVersion: v1
kind: Service
metadata:
  name: llm-worker-service
  namespace: llm-worker
spec:
  type: ClusterIP
  selector:
    app: llm-worker-deployment
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
